layout_spectrum: 0.3225806
color:
  saturation: 0.2340261
  lightness: 0.1953147
  brandStrength: 0.7040951
  rhythmicContrast: 0.03316522
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
typography_spectrum: 0.7723327
name: Dragan și Asociații
